---
- name: "frr | Deploy frr daemons"
  ansible.builtin.template:
    src: "daemons.j2"
    dest: "{{ hostvars[inventory_hostname]['frr_conf_dest'] + '/daemons' }}"
    owner: "{{ hostvars[inventory_hostname]['frr_user'] }}"
    group: "{{ hostvars[inventory_hostname]['frr_group'] }}"
    mode: "0640"
  notify:
    - "Restart frr"
- name: "frr | Deploy frr scripts"
  ansible.builtin.template:
    src: "frr_script.j2"
    dest: "{{ hostvars[inventory_hostname]['frr_conf_dest'] + '/scripts/' +
      script['name'] + '.lua' }}"
    owner: "{{ hostvars[inventory_hostname]['frr_user'] }}"
    group: "{{ hostvars[inventory_hostname]['frr_group'] }}"
    mode: "0640"
  loop: "{{ vars['frr_scripts_list'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "script"
    label: "{{ 'Deploy script: ' +
      hostvars[inventory_hostname]['frr_conf_dest'] + '/scripts/' +
      script['name'] + '.lua' }}"
  when:
    - "vars['frr_scripts_list'] is defined"
    - "vars['frr_scripts_list'] != ''"
    - "vars['frr_scripts_list'] != None"
    - "script['name'] is defined"
    - "script['name'] != ''"
    - "script['name'] != None"
    - "script['data'] is defined"
    - "script['data'] != ''"
    - "script['data'] != None"
  notify:
    - "Restart frr"
- name: "frr | Deploy frr configuration"
  ansible.builtin.template:
    src: "frr.j2"
    dest: "{{ hostvars[inventory_hostname]['frr_conf_dest'] + '/frr.conf' }}"
    owner: "{{ hostvars[inventory_hostname]['frr_user'] }}"
    group: "{{ hostvars[inventory_hostname]['frr_group'] }}"
    mode: "0640"
    validate: "vtysh -C -f %s"
  notify:
    - "Restart frr"
- name: "frr | Enable frr service"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['frr_service'] }}"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['frr'] is defined"
    - "hostvars[inventory_hostname]['frr'] != ''"
    - "hostvars[inventory_hostname]['frr'] |
       community.general.json_query(vars['frr_enable']) is defined"
    - "hostvars[inventory_hostname]['frr'] |
       community.general.json_query(vars['frr_enable']) == 'true'"
  vars:
    frr_enable: "[] | map(&enable || 'false', @) | [0]"
